cls  # unused variable (lovlig/config.py:46)
cls  # unused variable (lovlig/config.py:54)
exc_value  # unused variable (lovlig/state/manager.py:100)
traceback  # unused variable (lovlig/state/manager.py:100)
cls  # unused variable (lovlig/state/manager.py:127)
stage  # unused variable (lovlig/ui/reporter.py:50)
